### ISSUE TITLE
Date helper incorrectly calculates two dates being in the same week.

### ISSUE THREAD

**Issue by Dragas** [zexa/interview-task#12] opened 2019-05-21 15:36 UTC
The algorithm in question only seems to check whether or not day difference is 7 days or less. In addition it doesn't take into account mixed days. In addition, it fails for `2019-05-19, 2019-05-20` case. Since day difference is 1 day, yet the two are on different weeks. Since you can't use carbon, I would look into using `DateTime#format`. You can see accepted formats in this page https://www.php.net/manual/en/function.date.php

**Comment by zexa** [comment] 2019-05-21 15:51
@Dragas , 

```php
function sameWeek($d1, $d2) : bool
{
	$sameWeekDates[] = 
		date("Y-m-d", strtotime('monday this week', strtotime($d1)));
	$sameWeekDates[] = 
		date("Y-m-d", strtotime('tuesday this week', strtotime($d1)));
	$sameWeekDates[] = 
		date("Y-m-d", strtotime('wednesday this week', strtotime($d1)));
	$sameWeekDates[] = 
		date("Y-m-d", strtotime('thursday this week', strtotime($d1)));
	$sameWeekDates[] = 
		date("Y-m-d", strtotime('friday this week', strtotime($d1)));
	$sameWeekDates[] = 
		date("Y-m-d", strtotime('saturday this week', strtotime($d1)));
	$sameWeekDates[] = 
		date("Y-m-d", strtotime('sunday this week', strtotime($d1)));
	$sw = in_array($d2, $sameWeekDates);
	return $sw;
}

$s = sameWeek('2019-05-19', '2019-05-20');
var_dump($s);
```
```bash
$ php debug.php
bool(false)
```
The above code is a slightly adapted version of `ComissionsCalculator#sameWeek` which returns false for your specified unit test. This is the intended behavior here.

**Comment by zexa** [comment] 2019-05-21 16:50
Closing the issue as @Dragas was referencing an unused file.

**Closed by zexa** 2019-05-21 16:50 UTC
